version: "3.9"

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www/html
    depends_on:
      - mariadb
    networks:
      - codecraft-net

  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: codecraft
      MYSQL_USER: marina
      MYSQL_PASSWORD: marina
    ports:
      - "3308:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - codecraft-net

  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - codecraft-net

  node-service:
    build:
      context: .
      dockerfile: Dockerfile-node
    container_name: node-service
    ports:
      - "3000:3000"
    volumes:
      - ./avis-service:/app
    depends_on:
      - mongodb
    networks:
      - codecraft-net

networks:
  codecraft-net:

volumes:
  mariadb_data:
  mongodb_data:
